### ISSUE TITLE
PROTOCOL VERSION 1

### ISSUE THREAD

**Issue by guregu** [guregu/bbs#1]
## To-do until protocol is stable
- [x] Logging in, out, sessions
- [x] Listing threads
- [x] Reading threads
- [x] Posting threads
- [x] Replying to threads
- [x] Listing boards
- [ ] Thread list pagination?
- [ ] Secure log in
- [ ] Listing tags
- [ ] Listing users
- [ ] User profiles
- [ ] Search
- [ ] Registration, auto-registration
- [ ] Attachments, uploading
